//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitSpike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public int Dependents { get; set; }
        public string Title { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> AsvabScore { get; set; }
        public Nullable<decimal> PracticeScore { get; set; }
        public int EducationID { get; set; }
        public int PriorServiceID { get; set; }
        public int RoadmapID { get; set; }
        public string Id { get; set; }
        public int MStatusID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Education Education { get; set; }
        public virtual PriorService PriorService { get; set; }
        public virtual Roadmap Roadmap { get; set; }
        public virtual MStatu MStatu { get; set; }
    }
}
