//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitSpike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substep
    {
        public int SubstepID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string Notes { get; set; }
        public decimal Effort { get; set; }
        public int HeadingID { get; set; }
    
        public virtual Heading Heading { get; set; }
    }
}
